"""
Morning Weather Agent
----------------------
A minimal AI agent that demonstrates the core loop:
  1. Tool call  -> fetch raw weather data (Open-Meteo, free, no API key)
  2. Reasoning  -> Claude turns raw data into a short, friendly briefing
  3. Action     -> push the result to your phone via ntfy.sh

Now also includes a daily Hebrew vocabulary word, generated by Claude
and calibrated to an intermediate (bet+) level.

Environment variables required (set as GitHub Actions secrets):
  ANTHROPIC_API_KEY  - your Claude API key
  NTFY_TOPIC         - a secret topic name you invent, e.g. "yoni-weather-8f2k"
  CITY               - city name to geocode, e.g. "Tel Aviv"
"""

import os
import requests
import anthropic

CITY = os.environ.get("CITY", "Tel Aviv")
NTFY_TOPIC = os.environ["NTFY_TOPIC"]
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]


def geocode_city(city: str) -> dict:
    """Tool 1a: turn a city name into lat/lon."""
    resp = requests.get(
        "https://geocoding-api.open-meteo.com/v1/search",
        params={"name": city, "count": 1},
        timeout=10,
    )
    resp.raise_for_status()
    results = resp.json().get("results")
    if not results:
        raise ValueError(f"Could not geocode city: {city}")
    top = results[0]
    return {"lat": top["latitude"], "lon": top["longitude"], "name": top["name"]}


def fetch_weather(lat: float, lon: float) -> dict:
    """Tool 1b: fetch a 3-day high/low forecast."""
    resp = requests.get(
        "https://api.open-meteo.com/v1/forecast",
        params={
            "latitude": lat,
            "longitude": lon,
            "daily": "temperature_2m_max,temperature_2m_min,precipitation_probability_max",
            "temperature_unit": "fahrenheit",
            "timezone": "auto",
            "forecast_days": 3,
        },
        timeout=10,
    )
    resp.raise_for_status()
    return resp.json()["daily"]


def summarize_with_claude(client: anthropic.Anthropic, city: str, daily: dict) -> str:
    """Reasoning step: Claude turns raw numbers into a short briefing."""
    raw = "\n".join(
        f"{date}: high {hi}°F, low {lo}°F, rain chance {rain}%"
        for date, hi, lo, rain in zip(
            daily["time"],
            daily["temperature_2m_max"],
            daily["temperature_2m_min"],
            daily["precipitation_probability_max"],
        )
    )

    message = client.messages.create(
        model="claude-sonnet-5",
        max_tokens=200,
        messages=[
            {
                "role": "user",
                "content": (
                    f"You are a morning weather briefing assistant for {city}. "
                    f"Here is the raw 3-day forecast data:\n{raw}\n\n"
                    "Write a short (2-3 sentence), friendly push-notification-style "
                    "briefing covering today's high/low and anything notable "
                    "(rain, big swings). No markdown, no headers."
                ),
            }
        ],
    )
    return message.content[0].text.strip()


def hebrew_word_of_the_day(client: anthropic.Anthropic) -> str:
    """Reasoning step: Claude generates one new Hebrew vocabulary word,
    calibrated to an intermediate (bet+) Ulpan level — i.e. not
    beginner words, but not advanced/literary vocabulary either."""
    message = client.messages.create(
        model="claude-sonnet-5",
        max_tokens=200,
        messages=[
            {
                "role": "user",
                "content": (
                    "Give me one new Hebrew vocabulary word for a language "
                    "learner at an intermediate level (Israeli Ulpan bet+ "
                    "level — comfortable with basics and simple conversation, "
                    "but not yet advanced). Pick something a bit beyond what "
                    "a beginner would know — e.g. useful everyday verbs, "
                    "adjectives, or idioms rather than 'shalom'-tier basics. "
                    "Format as exactly 3 short lines, no markdown, no extra "
                    "commentary:\n"
                    "Line 1: the word in Hebrew script with niqqud\n"
                    "Line 2: transliteration and English meaning\n"
                    "Line 3: one short example sentence in Hebrew, then its "
                    "English translation in parentheses"
                ),
            }
        ],
    )
    return message.content[0].text.strip()


def send_push(title: str, body: str) -> None:
    """Action step: push the briefing to your phone via ntfy.sh."""
    # HTTP headers only allow Latin-1/ASCII characters, so any special
    # characters (em dashes, accented letters, etc.) must be stripped or
    # replaced before going into a header value like Title.
    safe_title = title.encode("ascii", "ignore").decode("ascii")
    requests.post(
        f"https://ntfy.sh/{NTFY_TOPIC}",
        data=body.encode("utf-8"),
        headers={"Title": safe_title},
        timeout=10,
    )


def main():
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    location = geocode_city(CITY)
    daily = fetch_weather(location["lat"], location["lon"])
    briefing = summarize_with_claude(client, location["name"], daily)
    hebrew_word = hebrew_word_of_the_day(client)

    combined = f"{briefing}\n\n\U0001F1EE\U0001F1F1 Word of the day:\n{hebrew_word}"
    send_push(f"Morning Brief - {location['name']}", combined)
    print(combined)  # also visible in GitHub Actions logs


if __name__ == "__main__":
    main()
